### PR TITLE
add support for 32bit linux

### PR DESCRIPTION
**Pull request by toepi**

### CODE REVIEW

**Comment by jlambert121** [comment]
Thanks - this is a nice enhancement.  Tests got upset with it though, I think it's just needing to set the architecture fact everywhere in the tests.

**Comment by toepi** [comment]
sry, but I was not able to run the test locally, they all failed :( - any hint how to run it local?

**Comment by jlambert121** [comment]
Assuming you have bundler installed, you can just do:

```
bundle install
bundle exec rake test
```

**Comment by toepi** [comment]
Thx, have not read your CONTRIBUTING-Guide :(.

**Comment by toepi** [comment]
@jlambert121: what's about this request? Any other issue, that i must/should fix?

**Comment by jlambert121** [comment]
Thanks!

**Pull request merged**
