### PR TITLE
Set kibana user home into kibana installation

### PR DESCRIPTION
**Pull request by nerzhul**
This fix kibana 4.2 writing files in its home directory

### CODE REVIEW

**Comment by jlambert121** [comment]
This is a breaking change (and I haven't been able to look at Kibana 4.2 yet), what changed with kibana that needs this?

**Comment by nerzhul** [comment]
@jlambert121 if i remember some configuration is written into it

**Comment by jlambert121** [comment]
Was this fixed in kibana 4.2.1? https://github.com/elastic/kibana/issues/5237

**Comment by nerzhul** [comment]
@jlambert121 i'm using kibana 4.3 and i kept the modified puppet version without testing baremetal

**Comment by jlambert121** [comment]
Sorry - I'm not following - I was wondering if this PR was still needed.  Potentially it was a bug that necessitated it in the first place.

**Comment by nerzhul** [comment]
yes i know but atm i haven't tested deploying kibana without this patch

**Pull request closed without merging**
