### PR TITLE
Added init SysV script funcationality to this module

### PR DESCRIPTION
**Pull request by soumentrivedi**
(applicable for RedHat 6 based OS, particularly for OEL6.6)

### CODE REVIEW

**Comment by jlambert121** [comment]
It's odd, for some reason init, install, and params files as changed - could you look at that?  I'd like this functionality and to get this merged though.  Thanks for getting tests right away.

**Comment by soumentrivedi** [comment]
Not sure why I did not get a notification for your comment @jlambert121 
I have added a legacy_service mode feature (in init, params and install) and performed a code formatting through Geppetto. That has probably removed some of the extra blank spaces and makes it appear that entire file has changed. Do you want me to undo the code formatting? Please let me know your thoughts on this.

**Comment by jlambert121** [comment]
Please.  I'm not sure what was actually changed around spacing.  My editor already uses two space soft tabs and trims all trailing white space.

**Comment by soumentrivedi** [comment]
Ok sure, will do that tonight and publish the changes.

**Comment by Savar** [comment]
@soumentrivedi the problem is your Windows CRLF line endings which should not be there..

I would appreciate this merge request to be merged.. if you want to I can create another pull request with your changes but without windows line endings or I could mail you a patch file (gist does not work because the characters aren't viewable so I cannot copy'n'paste it to the gist).

**Comment by soumentrivedi** [comment]
@Savar thanks for your comment, sorry I could not respond earlier. I have removed the windows line ending (it was something to do with my project preferences in my IDE). Thanks for pointing that out.

**Comment by jlambert121** [comment]
Awesome - thanks!

**Comment by jlambert121** [comment]
Releasing 2.1.0 shortly.

**Pull request merged**
